apps/home/urls.py
from turtle import home
from django import apps
from django.conf import settings
from django.urls import path, re_path
# from django.urls import url
from apps.home import views
from django.conf.urls.static import static

app_name = 'fileapp'
urlpatterns = [
    path('', views.index, name='indexname'),
    re_path('download', views.download_file,name='dwnfile'),
    re_path('filedwn', views.zipfiledown,name='dwnzipfile'),
    path('domainEntry', views.domainEntry, name = 'domainentry'),
    path('certexpirydetails', views.certexpirydetails, name = 'certexpirydetails'),
    path('crtgeneration', views.crtgeneration, name = 'crtgeneration'),
    path('reportgeneration', views.reportgenration, name = 'reportgeneration'),
    path('entry', views.entry, name = 'entry'),
    re_path('error',views.error,name='error')
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include  # add this
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))             # UI Kits Html files
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/templates/includes/footer.html
 <!-- Footer -->
<footer class="footer">
  <div class="row align-items-center justify-content-xl-between">
    <div class="col-xl-6">
    </div>
    <div class="col-xl-6">
      <div class="text-center text-xl-right text-muted">
        {% comment %} <a href="#" class="font-weight-bold ml-1" target="_blank">Copyright &copy; Digivalet.Inc.All rights reserved</a>  {% endcomment %}
      </div>
    </div>
  </div>
</footer>

apps/templates/includes/navigation.html
{% load static %}
{% comment %} <nav class="navbar navbar-expand-lg navbar-dark bg-default"> {% endcomment %}

  
  <nav class="navbar navbar-top navbar-expand navbar-dark  bg-default border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->          
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="{%static 'assets/img/brand/icon.png'%}">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{ request.user.username }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item">
              <i class="ni ni-user-run text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

apps/templates/includes/scripts.html
{% load static %}
  <script src="{%static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{%static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{%static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
  <script src="{%static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
  <script src="{%static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
  {% comment %} <script src="{%static 'assets/js/onload.js' %}"></script>
  <script src="{%static 'assets/js/domain.js' %}"></script>
  <script src="{%static 'assets/js/domainupdate.js' %}"></script>
  <script src="{%static 'assets/js/report.js' %}"></script>
  <script src="{%static 'assets/js/index.js' %}"></script> {% endcomment %}

apps/templates/includes/sidenav.html
{% load static %}
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header align-items-center">
      {% comment %} <a class="navbar-brand" href="/"> {% endcomment %}
        <img src="{% static 'assets/img/brand/logo.png' %}" width="270" height="150" alt="" >
      {% comment %} </a> {% endcomment %}
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            {% comment %} <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="{% url 'fileapp:index' %}"> {% endcomment %}
              <a class="nav-link {% if 'crt' in segment %} active {% endif %}" href="/">
              <i class="fa fa-cubes text-primary {% if 'index' in segment %} text-white {% endif %}"></i>
              <span class="nav-link-text ">CSR Generation</span>
            </a>
          </li>
          <li class="nav-item">
            {% comment %} <a class="nav-link {% if 'server' in segment %} active {% endif %}" href="{% url 'fileapp:crtgeneration' %}"> {% endcomment %}
              <a class="nav-link {% if 'domain' in segment %} active {% endif %}" href="/crtgeneration">
              <i class="fa fa-server text-primary {% if 'server' in segment %} text-white {% endif %}"></i>
              <span class="nav-link-text">CRT Generation</span>
            </a>
          </li>
          <li class="nav-item">
            {% comment %} <a class="nav-link {% if 'addServer' in segment %} active {% endif %}" href="{% url 'fileapp:serverRegistretion' %}"> {% endcomment %}
              <a class="nav-link {% if 'profile' in segment %} active {% endif %}" href="/domainEntry">
              <i class="fa fa-plus-square text-primary {% if 'addServer' in segment %} text-white {% endif %}"></i>
              <span class="nav-link-text">Domain Inventory</span>
            </a>
          </li>
          <li class="nav-item">
            {% comment %} <a class="nav-link {% if 'addServer' in segment %} active {% endif %}" href="{% url 'fileapp:serverRegistretion' %}"> {% endcomment %}
              <a class="nav-link {% if 'profile' in segment %} active {% endif %}" href="/entry">
              <i class="fa fa-random text-primary {% if 'addServer' in segment %} text-white {% endif %}"></i>
              <span class="nav-link-text">URL Inventory</span>
            </a>
          </li>
          <li class="nav-item">
            {% comment %} <a class="nav-link {% if 'unknownController' in segment %} active {% endif %}" href="{% url 'fileapp:unknownController' %}"> {% endcomment %}
              <a class="nav-link {% if 'tables' in segment %} active {% endif %}" href="/certexpirydetails">
              <i class="fa fa-hdd text-primary {% if 'unknownController' in segment %} text-white {% endif %}"></i>
              <span class="nav-link-text">CERT Expiry Details</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>