apps/home/urls.py
from turtle import home
from django import apps
from django.conf import settings
from django.urls import path, re_path
# from django.urls import url
from apps.home import views
from django.conf.urls.static import static

app_name = 'fileapp'
urlpatterns = [
    path('', views.index, name='indexname'),
    re_path('download', views.download_file,name='dwnfile'),
    re_path('filedwn', views.zipfiledown,name='dwnzipfile'),
    path('domainEntry', views.domainEntry, name = 'domainentry'),
    path('certexpirydetails', views.certexpirydetails, name = 'certexpirydetails'),
    path('crtgeneration', views.crtgeneration, name = 'crtgeneration'),
    path('reportgeneration', views.reportgenration, name = 'reportgeneration'),
    path('entry', views.entry, name = 'entry'),
    re_path('error',views.error,name='error')
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include  # add this
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))             # UI Kits Html files
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

apps/home/views.py
from pathoffile import BASE_DIR
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
import mimetypes
import shutil
import regex as re
from zipfile import ZipFile
import subprocess as sp
import pandas as pd
from slack_sdk import WebClient
from smtplib import SMTP
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import pandas as pd
from pretty_html_table import build_table
import regex as re
import os
from dotenv import load_dotenv
from datetime import timedelta,datetime
import json
# import numpy as np
# ----------------------------- loading credentials -----------------------------------------------------
load_dotenv('.env')
email_mine = os.getenv('email_mine')
password_mine = os.getenv('password_mine')
client = WebClient(token=os.getenv('token'))
channel_id = "D043GTBAVEV"
base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ------------------------------------------------------------------------------------------------------

def ids_func(i):
        result=client.chat_deleteScheduledMessage(
                channel=channel_id, scheduled_message_id=i)
        # print(result)
    
# delete the scheduled messages 
def delete_scheduled_messages(ids):
        x = lambda b : ids.replace(b,'')
        ids=x('[')
        ids=x(']')
        ids=x("'")
        ids = (ids.split(','))
        for i in ids:
            try:
                print("..................")
                print(i.strip())
                print("----------------------------------------------------------------------")
                print(ids_func(i.strip()))
                print("----------------------------------------------------------------------")
        
            except Exception as e:
                    print(e)
        return True
    
# ---------------------------------------------------       csrgeneration      ---------------------------------------------------

# generating the required csr.
def generatefile(das_fqdn_val):
    try:
        os.chdir('./'+'das_folders/'+das_fqdn_val)
        bash_csr_value = os.system('bash csrgenerate')
        try:
            if bash_csr_value is not None:
                out = sp.getoutput('bash verify '+ das_fqdn_val+'.csr')
                try:
                    if out is not None:
                        os.system('chmod +x '+das_fqdn_val+'.csr')
                        with open('csrfile.txt','w') as file:
                            file.write(out)
                        os.chdir('../../')
                        return out
                except:
                    pass
        except:
            pass
    except:
        return False

# replace context from the csrgenerate, openssl.cnf, verify.
def replace_files(das_fqdn_val,txt):
    try:
        files=['csrgenerate','openssl.cnf']
        replace_values_x=['<<DAS FQDN>>',"""DNS.1 = das.address-palace.digivalet.in\n\nDNS.2 = dvs.address-palace.digivalet.in\n\nDNS.3 = his.address-palace.digivalet.in"""]
        replace_values_y=[das_fqdn_val, txt]
        for i in range(2):
            with open( os.path.join(os.getcwd(),'das_folders',das_fqdn_val,files[i]), 'r') as file:
                x = replace_values_x[i]
                y = replace_values_y[i]
                data = file.read()
                data = data.replace(x, y)
            with open(os.path.join(os.getcwd(),'das_folders',das_fqdn_val,files[i]), 'w') as file:
                file.write(data)
    except:
        pass

# copy the required files
def copy_files(das_fqdn_val):
    try:
        l=['csrgenerate','openssl.cnf','verify']
        for i in range(3):
            src_path = os.path.join(os.getcwd(),'files',l[i])
            dst_path = os.path.join(os.getcwd(),'das_folders',das_fqdn_val,l[i])
            shutil.copy(src_path, dst_path)
            os.system('chmod +x '+os.path.join(os.getcwd(),'das_folders',das_fqdn_val,l[i]))
    except:
        pass

def csrgenerate(csrname,txt):
    try:
        os.mkdir('das_folders/'+csrname.strip())
        copy_files(csrname) 
        replace_files(csrname,txt)
        text_of_csr = generatefile(csrname)
        return text_of_csr
    except:
        return None

# CSR generation page.
@login_required(login_url="/login/")
def index(request):
    if request.method == 'POST':
        context = dict()
        try: 
            dns1 = (request.POST.get('dns1')).strip()
            dns2 = (request.POST.get('dns2')).strip()
            dns3 = (request.POST.get('dns3')).strip()
            dns4 = (request.POST.get('dns4')).strip()
            dns5 = (request.POST.get('dns5')).strip()
            dns6 = (request.POST.get('dns6')).strip()
            dns7 = (request.POST.get('dns7')).strip()
            dns8 = (request.POST.get('dns8')).strip()                   
            dns_name = [ i for i in [dns1,dns2,dns3,dns4,dns5,dns6,dns7,dns8] if i != '' and i != None ]                                        
            flag = False
            for i in dns_name:
                if 'das' in i:                  
                    dns_name_data = i
                    flag = True
            if not flag:
                dns_name_data =dns_name[0]
            dns_openssl = [] 
            count=1
            for i in dns_name:
                dns_openssl.append(('DNS.'+str(count)+'='+i))
                count+=1            
            txt = '\n'.join(dns_openssl)
            try:
                if not os.path.isdir(os.path.join(os.getcwd(),'das_folders',dns_name_data)):                       
                        text = csrgenerate(dns_name_data,txt)                                         
                        if text:                             
                            context['text'] =text                                
                            with open('temp.txt','w') as f:
                                f.write(dns_name_data)                                                             
                            data_unique = []                      
                            for i in dns_name:
                                if 'das' in i:
                                    dns_name.remove(i)
                                    data_unique.append(i)
                            for i in dns_name:
                                if i not in data_unique:
                                    data_unique.append(i)
                            data = ','.join(data_unique)                                
                            with open(os.path.join(os.getcwd() ,'das_folders' ,dns_name_data, 'all_fqdns.txt'), 'w') as f:
                                f.write(str(data))                                   
                else:                  
                    url = reverse('fileapp:indexname')
                    return HttpResponseRedirect(url)  
            except:
                pass
        except:
            print("Exception")
        context['segment'] = 'load_template'        
        html_template = loader.get_template('home/index.html')
        return HttpResponse(html_template.render(context, request))
    return render(request,'home/index.html')  

@login_required(login_url="/login/")
def download_file(request):
    try:
        if 'temp.txt' in os.listdir():       
            with open('temp.txt') as f:
                data = (f.read()).strip()                    
            filename = data+'.csr'            
            filepath = BASE_DIR + '/das_folders/'+data+'/'+data+'.csr' 
            path = open(filepath, 'r')            
            mime_type, _ = mimetypes.guess_type(filepath)
            context = HttpResponse(path, content_type=mime_type)
            context['Content-Disposition'] = "attachment; filename=%s" % filename
            os.remove(BASE_DIR+'/temp.txt')            
            return context
        url = reverse('fileapp:indexname')
        return HttpResponseRedirect(url)   
    except FileNotFoundError as e:
        return HttpResponse('''<h1>FILE NOT FOUND.</h1>''')                          

# ---------------------------------------------------       crtgeneration      ---------------------------------------------------

@login_required(login_url="/login/")   
def error(request):
    context = {}
    msg = f'''There are some files missing in the folder.'''
    context['msg'] = msg
    html_template = loader.get_template('home/page-404.html')
    return HttpResponse(html_template.render(context, request))


# compare the server.crt and the server.key.
def checkfile(name_of_file):
    sp.call(['chmod', '-R','755', os.path.join(os.getcwd(),'das_folders',name_of_file)])
    out1 = sp.getoutput("openssl x509 -noout -modulus -in "+os.path.join(os.getcwd(),'das_folders',name_of_file,'server.crt')+ "| openssl md5")
    value1 = out1.split('=')[-1]
    out2 = sp.getoutput("openssl rsa -noout -modulus -in "+os.path.join(os.getcwd(),'das_folders',name_of_file,'server.key')+ "| openssl md5")
    value2 = out2.split('=')[-1]
    if value1 == value2:
        return value1, value2, True
    else:
        return value1, value2, False

# unzip the uploaded file.
def unzipfile(name_of_file,uploaded_file):
    try:
        sp.call(['chmod', '-R','755', os.path.join(os.getcwd(),'das_folders',name_of_file)])
        with ZipFile(os.path.join(os.getcwd(),'das_folders',name_of_file,uploaded_file.name), 'r') as f:
            f.extractall(os.path.join(os.getcwd(),'das_folders',name_of_file))                    
        crt = (uploaded_file.name.split('.')[0])                    
        if '' in crt:
            crt = crt.split()[0]

apps/templates/home/crt.html
{% extends 'layouts/base.html' %}

{% comment %} {% block title %}crtGeneration{% endblock title %} {% endcomment %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% load static %}
    <!-- Header -->
    <div class="header bg-default pb-6">
      <div class="container-fluid">
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--6" >
            <div class="header-body">
                        <div class="row align-items-center py-4">
                            <div class="col-lg-6 col-7">
                              <h6 class="h2 text-white d-inline-block mb-0">CRT GENERATION</h6>
                            </div>
                        </div>
                <!-- Card stats -->
                <div class="card" style="background-image: url('{% static 'assets/img/brand/bg1.png' %}');">
                  <div class="card-body">
                      <form method="POST" enctype="multipart/form-data">
                          {% csrf_token %}
                      
                                    <div class="row">
                                      <select  id="folder" name="folder"  type="file" class='form-control'>
                                        <option selected="selected" enabled>Open CSR</option>
                                        {% for item in data %}
                                        <option>{{item}}</option>
                                        {% endfor %} 
                                      </select>
                                    </div>
                                    <br>
                                    <div class="row form-inline">
                                        <div class="col-md-12 text-right">
                                            <input class="btn btn-danger float-right" type="submit"  id="deleteFolder" name="deleteFolder" value="DELETE">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="text-center mx-4">
                                            <input type="file" id="zipfileUploaded" name="zipfileUploaded" class="btn btn-primary my-4" accept="zip,application/octet-stream,application/zip,application/x-zip,application/x-zip-compressed" />
                                        </div>
                                    </div>
                                    {% if error %}<div class='text=danger'>{{error}}</div>{% endif %}
                                    <div class="row">
                                        <div class="text-center mx-4">
                                            <button type="submit"  id="UploadfileSubmit"  name="UploadfileSubmit" class="btn btn-primary my-4">Submit</button>
                                        </div>
                                      </form>
                                        {% comment %} <a type="submit" class="btn btn-primary my-4" href="{% url 'fileapp:dwnfile' %} ">Download CSR</a>  {% endcomment %}
                                        {% comment %} {% if conform %} {% endcomment %}
                                        <a type="submit" class="btn btn-primary my-4" href="{% url 'fileapp:dwnzipfile' %} ">Download Zip</a> 
                                        {% comment %} {% endif %} {% endcomment %}
                                    </div>        
                      
                  </div>
                </div>
              </div>
    </div>
   
{% endblock content %}

{% block javascripts %}

{% load static %}
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>

{% endblock javascripts %}

apps/templates/home/entry.html
{% extends 'layouts/base.html' %}

{% comment %} {% block title %}csrGeneration {% endblock title %} {% endcomment %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
{% load static %}
<div class="header bg-default pb-6">
            <div class="container-fluid">
                    <div class="header-body">
                                <div class="row align-items-center py-4">
                                        <div class="col-lg-6 col-7">
                                            <h6 class="h2 text-white d-inline-block mb-0">URL Inventory</h6>
                                        </div>
                                </div>
                    </div>
            </div>
</div>
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
                <div class="card shadow " style="background-image: url('{% static 'assets/img/brand/bg1.png' %}');">
                        <div class="card-header bg-transparent border-0">
                                <h3 class="text-dark mb-0">ENTRY</h3>
                        </div>                       
                        <div class="container">                               
                                <!-- Card stats -->
                                <div class="row mt-3">
                                        {% for i, j in data.items%}
                                        <div class="col-xl-4 col-lg-4 col-md-6">
                                                <div class="card card-stats" id="accordion">
                                                <!-- Card body -->                                                              
                                                <div class="col">                                                                
                                                        <div class="card bg-light">                                                                                 
                                                                <div class="card-header collapsed card-link text-dark text-center" 
                                                                data-toggle="collapse" 
                                                                data-target="#collapse-{{forloop.counter}}">
                                                                {{i}}
                                                                </div>                                                                                
                                                                <div id="collapse-{{forloop.counter}}" 
                                                                class="collapse" 
                                                                data-parent="#accordion">
                                                                {% for k in j %} 
                                                                        <div class="text-dark text-center">{{k}}                                                                                                                                                                                                                                                                
                                                                        </div>
                                                                {% endfor %} 
                                                                </div>                                                                 
                                                        </div>
                                                </div>                                                                
                                                </div>
                                        </div>
                                        {% endfor%}

                                </div>
                        </div>

                </div>
        </div>
    </div>
           
</div>
  
{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

{% load static %}
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>

{% endblock javascripts %}

apps/templates/home/index.html
{% extends 'layouts/base.html' %}

{% load static %}
{% comment %} {% block title %} csrGenerstion {% endblock title %} {% endcomment %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Header -->
    <div class="header bg-default pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">CSR Generation</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-xl-12">
                {% comment %} <div class="card" style="background-image: url('{% static 'assets/img/brand/bg2.png' %}');"> {% endcomment %}
                    <div class="card" style="background-image: url('{% static 'assets/img/brand/bg1.png' %}');">
                    <div class="card-body">
                        {% comment %} <form method="POST"  onsubmit="return validateForm()" id="csrgen"> {% endcomment %}
                            <form method="POST">
                            {% csrf_token %}
                            <h6 class="heading-small text-muted mb-4">CSR GENERATION</h6>
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input">DNS.1</label>
                                                    <input type="dns" id="dns1" class="form-control text-dark" placeholder="DNS.1" name="dns1">
                                                    {% comment %} <label class="form-control-label text-danger" id="dns_inp1">Invalid DNS Entry</label> {% endcomment %}
                                                    
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input">DNS.2</label>
                                                    <input type="dns" id="dns2" class="form-control text-dark" placeholder="DNS.2" name="dns2">
                                                    {% comment %} <label class="form-control-label text-danger" id="dns_inp2">Invalid DNS Entry</label> {% endcomment %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input">DNS.3</label>
                                                    <input type="dns" id="dns3" class="form-control text-dark" placeholder="DNS.3" name="dns3">
                                                    {% comment %} <label class="form-control-label text-danger" id="dns_inp3">Invalid DNS Entry</label> {% endcomment %}
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input">DNS.4</label>
                                                    <input type="dns" id="dns4" class="form-control text-dark" placeholder="DNS.4" name="dns4">
                                                    {% comment %} <label class="form-control-label text-danger" id="dns_inp4">Invalid DNS Entry</label> {% endcomment %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input">DNS.5</label>
                                                    <input type="dns" id="dns5" class="form-control text-dark" placeholder="DNS.5" name="dns5">
                                                    {% comment %} <label class="form-control-label text-danger" id="dns_inp5">Invalid DNS Entry</label> {% endcomment %}
                                                    {% comment %} <label class="form-control-label text-danger" id="dns">Invalid public IP</label> {% endcomment %}
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input">DNS.6</label>
                                                    <input type="dns" id="dns6" class="form-control text-dark" placeholder="DNS.6" name="dns6">
                                                    {% comment %} <label class="form-control-label text-danger" id="dns_inp6">Invalid DNS Entry</label> {% endcomment %}
                                                    {% comment %} <label class="form-control-label text-danger" id="dns">Invalid local IP</label> {% endcomment %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input">DNS.7</label>
                                                    <input type="dns" id="dns7" class="form-control text-dark" placeholder="DNS.7" name="dns7">
                                                    {% comment %} <label class="form-control-label text-danger" id="dns_inp7">Invalid DNS Entry</label> {% endcomment %}
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="form-control-label" for="input">DNS.8</label>
                                                    <input type="dns" id="dns8" class="form-control text-dark" placeholder="DNS.8" name="dns8">
                                                    {% comment %} <label class="form-control-label text-danger" id="dns_inp8">Invalid DNS Entry</label> {% endcomment %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="pl-lg-4">
                                            <div class="row">
                                                <div class="text-center mx-4"> 
                                                    <div class="text-center">
                                                    <button type='submit' class="btn btn-primary my-4">ADD</button>
                                                    {% comment %} <input onclick="submitForm()" type="submit" value="Submit" id="btnsubmit" value="button"> {% endcomment %}
                                                    {% comment %} <input type="submit" class="btn btn-primary my-4" href=""  value="Add">  {% endcomment %}
                                                    {% comment %} <input type='reset'> {% endcomment %}
                                                </div>      
                                                </div>
                                            </div>
                                        </div>
                            </form>
                        </div>                                    
                        {% if text %}<div class="border: 5px " style="text-align: center;"><pre style="font-family: Georgia; font-size: 12pt; color: #000099;">{{text}}</pre></div><br><div class="text-center"> <a type="submit" class="btn btn-primary my-4" href="{% url 'fileapp:dwnfile' %} ">Download CSR</a> </div>                        
                        {% comment %} {% else %} </div><div>elseinside</div><a type="submit" class="btn btn-primary my-4" href="{% url 'fileapp:dwnfile' %} ">Download CSR</a> </div> {% endcomment %}
                        {% endif %}     
                    </div>                
            </div> 
        </div>
         {% if msg %}<div>{{msg}}</div><div class="text-danger">{{msg}}</div>{% endif %}
      {% include "includes/footer.html" %}
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
{% load static %}
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>
{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends 'layouts/error.html' %}

{% comment %} {% block title %} Error {% endblock title %} {% endcomment %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}
<div class="main-content">
  {% comment %} {% include "includes/navigation-fullscreen.html" %} {% endcomment %}
  <!-- Header -->


{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              {% comment %} <div class="text-muted text-center mt-2 mb-3">
               Oups! Error 404     
              </div> {% endcomment %}

              <div class="text-center mb-4">
              <h2>
                {{msg}}                
              </h2>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}